### ISSUE TITLE
Integration testing

### ISSUE THREAD

**Issue by JamesLefrere** [JoinColony/tailor#31]
As a lighthouse maintainer, I want a simple integration testing environment with an example contract, so that I can see that the library works as intended.

- [ ] Set up Ganache
- [ ] Compile and deploy example contract
- [ ] Create a Lighthouse instance
- [ ] Load the contract
- [ ] Interact with the contract
  - [ ] Constants
  - [ ] Methods
  - [ ] Events
- [ ] Override the contract
